version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
    include: "scope"
  groups:
    mui:
      patterns:
      - "@mui/*"
      - "@emotion/*"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react*"
    eslint:
      patterns:
      - "eslint*"
    vite:
      patterns:
      - "vite"
      - "@vitejs/*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  commit-message:
    prefix: "ci"
    include: "scope"
