export const modelStore = (_set, _get) => ({
  models: [
    {
      name: "GPT-5.5",
      items: [
        {
          name: "GPT-5.5 (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 2500,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 5.0,
        },
        {
          name: "GPT-5.5 (Data Zone)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 2500,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 5.5,
        },
      ],
    },
    {
      name: "GPT-5.4",
      items: [
        {
          name: "GPT-5.4 (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 2500,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 2.5,
        },
        {
          name: "GPT-5.4 (Data Zone)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 2500,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 2.75,
        },
        {
          name: "GPT-5.4 mini (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.62,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.75,
        },
        {
          name: "GPT-5.4 nano (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 2.46,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.2,
        },
      ],
    },
    {
      name: "GPT-5.3",
      items: [
        {
          name: "GPT-5.3 Codex (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 1.75,
        },
      ],
    },
    {
      name: "GPT-5.2",
      items: [
        {
          name: "GPT-5.2 (Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 1.75,
        },
        {
          name: "GPT-5.2 (Data Zone)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.0,
          maxImageDimension: 2048,
          costPerMillionTokens: 1.925,
        },
      ],
    },
    {
      name: "GPT-5.1",
      items: [
        {
          name: "GPT-5.1 (Global)",
          tokensPerTile: 140,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 70,
          costPerMillionTokens: 1.25,
        },
        {
          name: "GPT-5.1 (Data Zone)",
          tokensPerTile: 140,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 70,
          costPerMillionTokens: 1.375,
        },
      ],
    },
    {
      name: "GPT-5",
      items: [
        {
          name: "GPT-5 (2025-08-07 - Global)",
          tokensPerTile: 140,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 70,
          costPerMillionTokens: 1.25,
        },
        {
          name: "GPT-5 (2025-08-07 - Data Zone)",
          tokensPerTile: 140,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 70,
          costPerMillionTokens: 1.375,
        },
      ],
    },
    {
      name: "o-series",
      items: [
        {
          name: "o4-mini (2025-04-16 - Global)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.72,
          maxImageDimension: 2048,
          costPerMillionTokens: 1.1,
        },
        {
          name: "o4-mini (2025-04-16 - Data Zone)",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.72,
          maxImageDimension: 2048,
          costPerMillionTokens: 1.21,
        },
        {
          name: "o3 (2025-04-16)",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 2,
        },
      ],
    },
    {
      name: "Image Generation",
      items: [
        {
          name: "gpt-image-2 (Global)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 8,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1.5 (Global)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 8,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1.5 (Data Zone)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 8.8,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1-mini (Global)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 2.5,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1 (Global)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 10,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1 (Data Zone)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 11,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
        {
          name: "gpt-image-1 (Standard)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 11,
          comment:
            "This calculator only provides the input tokens consumed by the image generation model, not the output tokens for the images generated by the model.",
        },
      ],
    },
    {
      name: "Retiring",
      items: [
        {
          name: "GPT-4.1 (2025-04-14 - Global)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2,
        },
        {
          name: "GPT-4.1 (2025-04-14 - Data Zone)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.2,
        },
        {
          name: "GPT-4.1 mini (2025-04-14 - Global)",
          retirementDate: "Oct 2026",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.62,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.4,
        },
        {
          name: "GPT-4.1 mini (2025-04-14 - Data Zone)",
          retirementDate: "Oct 2026",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 1.62,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.44,
        },
        {
          name: "GPT-4.1 nano (2025-04-14 - Global)",
          retirementDate: "Oct 2026",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 2.46,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.1,
        },
        {
          name: "GPT-4.1 nano (2025-04-14 - Data Zone)",
          retirementDate: "Oct 2026",
          tokenizationType: "patch",
          patchSize: 32,
          patchBudget: 1536,
          tokenMultiplier: 2.46,
          maxImageDimension: 2048,
          costPerMillionTokens: 0.11,
        },
        {
          name: "GPT-4o (2024-11-20 - Global)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.5,
        },
        {
          name: "GPT-4o (2024-11-20 - Data Zone)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.75,
        },
        {
          name: "GPT-4o (2024-08-06 - Global)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.5,
        },
        {
          name: "GPT-4o (2024-08-06 - Data Zone)",
          retirementDate: "Oct 2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.75,
        },
        {
          name: "o1 (2024-12-17 - Global)",
          retirementDate: "Jul 2026",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 15,
        },
        {
          name: "o1 (2024-12-17 - Data Zone)",
          retirementDate: "Jul 2026",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 16.5,
        },
        {
          name: "o1 (2024-12-17 - Standard)",
          retirementDate: "Jul 2026",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 16.5,
        },
        {
          name: "computer-use-preview",
          retirementDate: "Jul 2026",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 3,
          comment:
            "This calculator only provides the input tokens consumed by the screenshot images processed by the computer-use-preview model, not the entire execution. Images are calculated based on the display width and height defined in the Computer Use tool. The quantity of images will be based on the number of actions the model requires to complete the task.",
        },
        {
          name: "GPT-4.5-Preview (2025-02-27)",
          retirementDate: "2026",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 75,
        },
      ],
    },
  ],
});
