export const modelStore = (set, get) => ({
  models: [
    {
      name: "GPT-4.1",
      items: [
        {
          name: "GPT-4.1 (2025-04-14 - Global)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2,
        },
      ],
    },
    {
      name: "o-series",
      items: [
        {
          name: "o3 (2025-04-16)",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 10,
        },
        {
          name: "o1 (2024-12-17 - Global)",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 15,
        },
        {
          name: "o1 (2024-12-17 - Data Zone)",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 16.5,
        },
        {
          name: "o1 (2024-12-17 - Standard)",
          tokensPerTile: 150,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 75,
          costPerMillionTokens: 16.5,
        },
      ],
    },
    {
      name: "GPT-4o",
      items: [
        {
          name: "GPT-4o (2024-11-20 - Global)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.5,
        },
        {
          name: "GPT-4o (2024-11-20 - Data Zone)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.75,
        },
        {
          name: "GPT-4o (2024-11-20 - Standard)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 3.025,
        },
        {
          name: "GPT-4o (2024-08-06 - Global)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.5,
        },
        {
          name: "GPT-4o (2024-08-06 - Data Zone)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.75,
        },
        {
          name: "GPT-4o (2024-08-06 - Standard)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 2.75,
        },
        {
          name: "GPT-4o (2024-05-13)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 5,
        },
      ],
    },
    {
      name: "GPT-4o-mini",
      items: [
        {
          name: "GPT-4o-mini (2024-07-18 - Global)",
          tokensPerTile: 5667,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 2833,
          costPerMillionTokens: 0.15,
        },
        {
          name: "GPT-4o-mini (2024-07-18 - Data Zone)",
          tokensPerTile: 5667,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 2833,
          costPerMillionTokens: 0.165,
        },
        {
          name: "GPT-4o-mini (2024-07-18 - Standard)",
          tokensPerTile: 5667,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 2833,
          costPerMillionTokens: 0.165,
        },
      ],
    },
    {
      name: "Image Generation",
      items: [
        {
          name: "gpt-image-1 (Global)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 10,
        },
        {
          name: "gpt-image-1 (Data Zone)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 11,
        },
        {
          name: "gpt-image-1 (Standard)",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 512,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 11,
        },
      ],
    },
    {
      name: "Preview",
      items: [
        {
          name: "computer-use-preview",
          tokensPerTile: 129,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 65,
          costPerMillionTokens: 3,
          comment:
            "This calculator only provides the input tokens consumed by the screenshot images processed by the computer-use-preview model, not the entire execution. Images are calculated based on the display width and height defined in the Computer Use tool. The quantity of images will be based on the number of actions the model requires to complete the task.",
        },
        {
          name: "GPT-4.5-Preview (2025-02-27)",
          tokensPerTile: 170,
          maxImageDimension: 2048,
          imageMinSizeLength: 768,
          tileSizeLength: 512,
          baseTokens: 85,
          costPerMillionTokens: 75,
        },
      ],
    },
  ],
});
